### ISSUE TITLE
Translate Karmada API document into Chinese

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/website#483]
**What would you like to be added**:

We have just added the Karmada API document #476, but the content is in English. Because we currently support Simplified Chinese and English, we need to translate the API document into Chinese.

At present, we do not have an automatic translation tool script to complete this tool. Therefore, drawing on the working method of Kubernetes webstite, we will present the documents to be translated in the form of a list. Anyone who is interested in participating in the translation work can receive the documents they are interested in. Partially, thanks.

- [x] Karmada API @XiShanYongYe-Chang  #487
- [x] Auto Scaling Resources @XiShanYongYe-Chang #497 
  - [x] CronFederatedHPA v1alpha1
  - [x] FederatedHPA v1alpha1
- [x] Cluster Resources @XiShanYongYe-Chang #498 
  - [x] Cluster v1alpha1
- [x] Common Definitions @XiShanYongYe-Chang #503 
  - [x] DeleteOptions
  - [x] LabelSelector
  - [x] ListMeta
  - [x] NodeSelectorRequirement
  - [x] ObjectMeta
  - [x] Patch
  - [x] Quantity
  - [x] Status
  - [x] TypedLocalObjectReference
- [x] Common Parameters @XiShanYongYe-Chang #504
  - [x] Common Parameters
- [x] Config Resources @XiShanYongYe-Chang #499 
  - [x] ResourceInterpreterCustomization v1alpha1
  - [x] ResourceInterpreterWebhookConfiguration v1alpha1
- [ ] Networking Resources @XiShanYongYe-Chang #502 
  - [ ] MultiClusterIngress v1alpha1
  - [ ] MultiClusterService v1alpha1
- [x] Policy Resources @XiShanYongYe-Chang #493 
  - [x] ClusterOverridePolicy v1alpha1
  - [x] ClusterPropagationPolicy v1alpha1
  - [x] FederatedResourceQuota v1alpha1
  - [x] OverridePolicy v1alpha1
  - [x] PropagationPolicy v1alpha1
- [x] Search Resources @XiShanYongYe-Chang #500
  - [x] ResourceRegistry v1alpha1
- [x] Work Resources @XiShanYongYe-Chang #492 
  - [x] ClusterResourceBinding v1alpha2
  - [x] ResourceBinding v1alpha2 
  - [x] Work v1alpha1

/help

You can reply to the content you want to do in the comments, I will assign the corresponding task to you, thanks~
